services:
  tank-pair-1:
    container_name: tank-pair-1
    build: ./tank-pair-1
    privileged: true
    user: root
    ports:
      - "1880:1880"
      - "10502:10502"
    volumes:
      - ./tank-pair-1:/data

  # tank-pair-2:
  #   container_name: tank-pair-2
  #   build: ./tank-pair-2
  #   privileged: true
  #   user: root
  #   ports:
  #     - "1881:1880"
  #     - "10503:10502"
  #   volumes:
  #     - ./tank-pair-2:/data

  # tank-pair-3:
  #   container_name: tank-pair-3
  #   build: ./tank-pair-3
  #   privileged: true
  #   user: root
  #   ports:
  #     - "1882:1880"
  #     - "10504:10502"
  #   volumes:
  #     - ./tank-pair-3:/data

  central-control:
    container_name: central-control
    build: ./central-control
    privileged: true
    user: root
    ports:
      - "1879:1880"
    volumes:
      - ./central-control:/data
